# Generated by Django 4.2.1 on 2023-05-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='size_name',
        ),
    ]
