# Generated by Django 4.2.1 on 2023-07-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cart.order'),
            preserve_default=False,
        ),
    ]
